eval_dataset: "davis"
movi_f_root: /path/to/movi-f/dataset     # TODO: set path to TAP-Vid Kubric Movi-F dataset (see dataset/README.md)
tapvid_root: /path/to/tapvid/davis/pkl  # TODO: set path to tapvid_davis.pkl

checkpoint_path: null # if None, will not load any checkpoint and start training from scratch
model_save_path: "checkpoints/track_on2"

frame_sampling: "uniform"
frame_sample_ratio: 2.0

input_size: [384, 512]
N: 384
T: 48

M: 24
D: 256
K: 16
decoder_layer_num: 3
predicton_head_layer_num: 3
rerank_layer_num: 3

vit_backbone: "dinov3_s_plus"
vit_upsample_factor: 1.143

M_i: 72
delta_v: 0.8

lambda_patch_cls: 3.0

evaluation: False
epoch_num: 200
lr: 0.0005
wd: 0.00001
bs: 1
grad_checkpoint: True
amp: True
seed: 1234